version: "3.7"

services:
  web:
    image: nginx:latest
    ports:
        - "172.18.238.1:8080:80"
    volumes:
        - ./www:/var/www
        - ./config/site.conf:/etc/nginx/conf.d/site.conf
        - ./log:/var/log/nginx
    depends_on: 
        - php
    networks:
      back:
        ipv4_address: 172.18.238.2
      default:
  php:
    build: ./config/docker/php
    volumes:
        - ./www:/var/www
        - ./config/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    depends_on:
        - composer

  composer:
    image: composer:latest
    command: ["composer", "install"]
    volumes:
        - ./www:/app

networks:
    back:
      driver: bridge
      ipam:
       driver: default
       config:
         - subnet: 172.18.238.0/24
    default:
      driver: bridge